### ISSUE TITLE
Kit Options

### ISSUE THREAD

**Issue by makshh** [bdkjones/CodeKit#219]
**Quick, short summary:**

I can't change options in "Kit Options".

**Exact steps to reproduce:**

Try to change "Same folder as the source file" to "This folder:" in "Kit Options", then jump to another option (for example "Less") and go back to "Kit Options". Changes are not applied (still "Same folder as the source file" radio button is checked).

macOS Sierra 10.12.1
CodeKit 3.0 - Build 25378

**Comment by bdkjones** [comment]
Are you in New Project Defaults, or just regular Project Settings?

**Comment by makshh** [comment]
I think it's regular.

[[http://prntscr.com/czqtuv]]
[[http://prntscr.com/czqu5l]]
[[http://prntscr.com/czque9]]

![Image](http://prntscr.com/czqtuv)

**Comment by makshh** [comment]
I can change the path on the file basis and it works, but I would like to set it globally.

http://prntscr.com/czsusb

**Comment by makshh** [comment]
Check this out

![](http://i.giphy.com/l0MYwOnQxOckmAHU4.gif)

**Comment by bdkjones** [comment]
Ah, I see why this is happening. It is indeed a bug. When you modify any output options for Kit, you're actually going to change the options on the LAST language that you had selected. Will push an update to fix.

**Comment by makshh** [comment]
Great.

This is actually the opposite. When you modify any output options form any Language, you're actually going to change the options on the Kit language. (but - these changes are not saved in the config.codekit3 file)

**Comment by bdkjones** [comment]
It just *looks* that way because the UI elements aren't bound properly to the model object that stores Kit output path information. So you're seeing the inputs you added to Slim because the textfields aren't updated when you switch from Slim to Kit.

**Comment by bdkjones** [comment]
In other words, the fields just keep showing whatever they had on the last language you selected.

**Comment by makshh** [comment]
Oh, now I understand, waiting for fix :)

**Comment by bdkjones** [comment]
Use the Tasks menu command to set build folder defaults in the meantime. It’s not affected by this and will get you want you wanted.

**Comment by makshh** [comment]
![](http://i.giphy.com/l0MYONJgpkS6FyDcY.gif)

**Comment by bdkjones** [comment]
@makshh That's not a bug. You should watch the screencast on New Project Defaults. You're adjusting them, then adding back to the app a project that already has settings assigned to it. "Defaults for New Projects" means NEW. If a project has already been in CodeKit before, its settings are always maintained; the defaults are not applied.

**Comment by makshh** [comment]
Am I not creating new project on this GIF? The folder I dragged to the CodeKit was empty, so I assume this is a new project (without config.codekit3).

**Comment by makshh** [comment]
Things I found aren't working in New Defaults:

1. UglifyJS, ESLint, JSLint, JSHint and CoffeeLint rules are not applied to the New Projects (other options are working).
2. Babel Syntax plugins, ES3 Transform Plugins etc. are not saving at all (try to change some options in New Defaults, click Done and go back to New Defaults).
3. When you apply a global for example to ESLint, this globals are copied to others (JSLint, JSHint - it may not be a bug - just saying).

**Comment by bdkjones** [comment]
Okay. 

(1) is definitely a bug. I've tracked it down and implemented a fix. Will push an update.

(3) is expected behavior. globals are shared across checkers because it's not like your code is going to change if you pick JSHint instead of ESLint.

(2) I'm looking into now.

**Comment by bdkjones** [comment]
Annnnd here's the problem:

<img width="921" alt="screen shot 2016-10-28 at 21 46 42" src="https://cloud.githubusercontent.com/assets/926566/19827252/15b1c61c-9d58-11e6-8926-0fbbda2b9771.png">

`babelTransformers` isn't a thing. It's `babelPlugins`. But I built the goddamn app to be so fault tolerant, that this didn't cause a crash, it just fell back on the canonical, initial Babel values that I ship CodeKit with.

**Comment by bdkjones** [comment]
Fixed for 3.0.1

**Comment by makshh** [comment]
Hi again, I still have problem with New Projects (CodeKit 3.0.3). I have checked several options in ESLint New Projects Defaults and when I'm creating a new project (I'm dragging empty folder to CodeKit) options are not applied.

**Comment by bdkjones** [comment]
Are you sure the folders you're dragging don't have CodeKit configuration files in them?

**Comment by makshh** [comment]
Sure.

**Comment by makshh** [comment]
3.0.4 - still defaults for for example ESLint doesn't apply to new projects.

1. Project defaults.

![1](http://image.prntscr.com/image/492eb22579b54ee5acbb928d7a12d289.png)

2. New project (new folder without codekit config file).

![2](http://image.prntscr.com/image/d442044465074c53aef3d346df5557a3.png)
