### ISSUE TITLE
Error with Preview Server on Chrome 59

### ISSUE THREAD

**Issue by richardsison** [bdkjones/CodeKit#371]
**Quick, short summary:**
When trying to access the preview server on Chrome 59, I get the following error:

> This site can’t provide a secure connection
> localhost doesn't adhere to security standards.
> ERR_SSL_SERVER_CERT_BAD_FORMAT

In Chrome (58), Safari (10.1.1) and Firefox () I'm given a step which allows me to ["proceed with warning"](http://share.richardsison.com/5IRgws). But not in the latest version of Chrome (59).

The project is using SSL in Codekit.

**Expected results:**
I expected to see a warning page with an option to proceed via adding a certificate/exception.

**Actual results:**
An error screen with no options to fix the issue or proceed.
http://share.richardsison.com/a8VCx

**Exact steps to reproduce:**
Preview any project using Chrome 59 where SSL is enabled.
I was replicating the steps for the remote styling feature in this video: https://youtu.be/F-60yBpsEpw

**A link to download a simplified project or file that shows the issue:**

**Your configuration (any details about your system that you think might be relevant)**
* Chrome 59
* In Codekit:
** SSL enabled
** External Server set up with "Override remote CSS with local copies" enabled.

**Comment by kulincz** [comment]
Same issue here.

**Comment by Protohominid** [comment]
+1

Is there no way to force chrome to accept all certificates from Codekit?

**Comment by bdkjones** [comment]
Yep. There are some shenanigans going on with Chromium 59 because they switched certificate parsers on Mac, apparently: https://bugs.chromium.org/p/chromium/issues/detail?id=715969

There are a couple things in that thread that I'm going to try in order to get the self-signed certs to work in Chrome 59+. They also merged a fix for at least one of the causes of this error, which should go live in Chrome 60.

**Comment by bdkjones** [comment]
Yep. Using that thread above, I was able to resolve the issue. The new certificate parser in Chrome 59+ doesn't handle version 1 certificates correctly. You have to explicitly set the version to 3. 

Fucking hilariously, to do that, you have to set the version number to `2`. Because apparently they're zero-indexed, so `v0` is actually `version 1`:

<img width="980" alt="screen shot 2017-07-13 at 15 52 29" src="https://user-images.githubusercontent.com/926566/28191170-a1d9f3fc-67e3-11e7-8d5a-694e0bfa0ddd.png">

TLS is such a nightmare.

**Comment by bdkjones** [comment]
Fixed for the next release. I'll try to get that out in the next few days. In the meantime, Safari is your friend---just add the cert to the keychain on OS X following the instructions in the overlay.

**Comment by Protohominid** [comment]
Thanks Bryan!

**Comment by adrianpauly** [comment]
Hi, I'm sorry but I read the thread mentioned by Bryan and I don't understand where I'm supposed to change that x509 setting.

Also I'm on Chrome 60 now and still having the problem.

**Comment by bdkjones** [comment]
There is no setting for you to change. It's a workaround I have to implement in code.

**Comment by bdkjones** [comment]
Fixed for the next release. Attempting to get that pushed tonight or tomorrow, finally.

**Comment by ginader** [comment]
@bdkjones did the update get pushed? Which version of codekit should I be looking for? I still see Version 3.2 as latest. BTW: Chrome 60 is out but I see the same issue there :-/

**Comment by bdkjones** [comment]
No, the update has not gone live yet.

**Comment by ginader** [comment]
@bdkjones thanks Bryan! Any (rough) ETA?

**Comment by ciprianmp** [comment]
@bdkjones Hi Bryan. Where (I mean in which apache/server file) did you change 0x0 to 0x2? Neither of my crt, csr or key files have a 0x sequence.
Thanks in advance.

**Comment by bdkjones** [comment]
I’m afraid I don’t understand your question.

**Comment by ciprianmp** [comment]
Sorry, I could not reply to your actual (old) comment. You said the fix is replacing v1 with v3 (0x0 with 0x2) but in which file?

**Comment by bdkjones** [comment]
You don’t need to worry about it; it was a fix I implemented. Make sure you’re running CodeKit 3.4.2 and you’re all set.

**Comment by ciprianmp** [comment]
Thank you. I thought the fix applies to a server not running CodeKit necessarily.
